import React from 'react'
import { Shield, FileText, RefreshCw, CheckCircle } from 'lucide-react'

const page = () => {
  return (
    <div className='min-h-screen bg-gradient-to-br from-purple-50 via-blue-50 to-indigo-100 dark:from-gray-900 dark:via-purple-950 dark:to-black'>
      {/* Header */}
      <div className='bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border-b border-purple-100 dark:border-purple-800'>
        <div className='max-w-6xl mx-auto px-4 py-5'>
          <div className='text-center'>
            <h1 className='flex justify-center items-center gap-4 text-4xl font-bold bg-gradient-to-r from-purple-600 via-blue-600 to-indigo-600 bg-clip-text text-transparent mb-2'>
                <div className='p-3 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl shadow-lg'>
                <FileText className='h-8 w-8 text-white' />
              </div>
              Legal Information
            </h1>
            <p className='text-gray-600 dark:text-gray-300 text-lg'>
              Terms & Conditions, Privacy Policy, and Refund Information
            </p>
          </div>
        </div>
      </div>

      <div className='max-w-6xl mx-auto px-6 py-6'>
        {/* Terms & Conditions Section */}
        <div className='bg-white/70 dark:bg-gray-800/70 backdrop-blur-sm rounded-3xl p-8 shadow-2xl border border-purple-100 dark:border-purple-800 mb-8'>
          <div className='flex items-center gap-3 mb-6'>
            <Shield className='h-6 w-6 text-purple-600' />
            <h2 className='text-2xl font-bold text-gray-800 dark:text-gray-200'>
              Terms & Conditions
            </h2>
          </div>
          <div className='prose prose-gray dark:prose-invert max-w-none'>
            <div className='grid gap-4 text-sm leading-relaxed text-gray-700 dark:text-gray-300'>
              <div className='flex items-start gap-3'>
                <CheckCircle className='h-4 w-4 text-green-500 mt-1 flex-shrink-0' />
                <p><strong>A.</strong> This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
              </div>
              
              <div className='flex items-start gap-3'>
                <CheckCircle className='h-4 w-4 text-green-500 mt-1 flex-shrink-0' />
                <p><strong>B.</strong> This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of OptiSense AI Platform.</p>
              </div>
              
              <div className='flex items-start gap-3'>
                <CheckCircle className='h-4 w-4 text-green-500 mt-1 flex-shrink-0' />
                <p><strong>C.</strong> The Platform is owned by OptiSense AI, providing AI-powered assistance services through our platform.</p>
              </div>
              
              <div className='flex items-start gap-3'>
                <CheckCircle className='h-4 w-4 text-green-500 mt-1 flex-shrink-0' />
                <p><strong>D.</strong> Your use of the Platform and services and tools are governed by the following terms and conditions. By mere use of the Platform, You shall be contracting with OptiSense AI and these terms and conditions constitute Your binding obligations.</p>
              </div>
              
              <div className='flex items-start gap-3'>
                <CheckCircle className='h-4 w-4 text-green-500 mt-1 flex-shrink-0' />
                <p><strong>E.</strong> For the purpose of these Terms of Use, "you", "your" or "user" shall mean any natural or legal person who has agreed to become a user on the Platform.</p>
              </div>

              <div className='flex items-start gap-3'>
                <CheckCircle className='h-4 w-4 text-green-500 mt-1 flex-shrink-0' />
                <p><strong>F.</strong> ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE.</p>
              </div>
              
              <div className='mt-6'>
                <h3 className='text-lg font-semibold mb-4 text-gray-800 dark:text-gray-200'>Key Terms of Service:</h3>
                <div className='grid gap-3'>
                  {[
                    "Provide true, accurate and complete information during registration",
                    "Use the platform solely at your own risk and discretion", 
                    "Respect intellectual property rights and platform contents",
                    "Pay associated charges for availing premium services",
                    "Use the platform only for lawful purposes",
                    "Indemnify OptiSense AI from any claims due to your breach"
                  ].map((term, index) => (
                    <div key={index} className='flex items-start gap-3'>
                      <CheckCircle className='h-4 w-4 text-blue-500 mt-1 flex-shrink-0' />
                      <span className='text-sm'>{term}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Privacy Policy Section */}
        <div className='bg-white/70 dark:bg-gray-800/70 backdrop-blur-sm rounded-3xl p-8 shadow-2xl border border-purple-100 dark:border-purple-800 mb-8'>
          <div className='flex items-center gap-3 mb-6'>
            <Shield className='h-6 w-6 text-blue-600' />
            <h2 className='text-2xl font-bold text-gray-800 dark:text-gray-200'>
              Privacy Policy
            </h2>
          </div>
          
          <div className='prose prose-gray dark:prose-invert max-w-none'>
            <div className='text-sm leading-relaxed text-gray-700 dark:text-gray-300 space-y-6'>
              <div className='bg-blue-50 dark:bg-blue-900/20 p-6 rounded-lg border border-blue-200 dark:border-blue-800'>
                <h3 className='font-semibold text-blue-800 dark:text-blue-300 mb-3'>Our Commitment to Privacy</h3>
                <p>We highly prioritize your concerns regarding online privacy and security during your visits and transactions on our website. We are dedicated to ensuring that the information you provide remains secure and is used appropriately.</p>
              </div>
              
              <div>
                <h3 className='font-semibold text-gray-800 dark:text-gray-200 mb-3'>Data Collection by OptiSense AI:</h3>
                <p>OptiSense AI collects essential information necessary to fulfill your requests, which may include your name, email, and preferences. This information is gathered when you use our AI services or subscribe to notifications. Your data is transmitted using the highest level of encryption to ensure utmost safety and security.</p>
              </div>
              
              <div>
                <h3 className='font-semibold text-gray-800 dark:text-gray-200 mb-3'>Cookie Usage:</h3>
                <p>During your website navigation, we utilize "cookies" or small pieces of tracking data to gather insights into your preferences and interactions. This data is not linked to individual customers, and we strictly refrain from using cookies to store confidential information.</p>
              </div>
              
              <div>
                <h3 className='font-semibold text-gray-800 dark:text-gray-200 mb-3'>Information Usage:</h3>
                <p>Our primary purpose for collecting information is to facilitate service delivery and customer support. We leverage this information to enhance our AI services, platform content, and user experience.</p>
              </div>

              <div>
                <h3 className='font-semibold text-gray-800 dark:text-gray-200 mb-3'>Business Name - Nilesh Rana</h3>
              </div>
              
              <div className='bg-green-50 dark:bg-green-900/20 p-4 rounded-lg border border-green-200 dark:border-green-800'>
                <h3 className='font-semibold text-green-800 dark:text-green-300 mb-2'>Security Measures:</h3>
                <p>We employ secure socket layer (SSL) technology and reasonable internet security measures to prevent unauthorized access, maintain data accuracy, and ensure appropriate use of information.</p>
              </div>
            </div>
          </div>
        </div>

        {/* Refund Policy Section */}
        <div className='bg-white/70 dark:bg-gray-800/70 backdrop-blur-sm rounded-3xl p-8 shadow-2xl border border-purple-100 dark:border-purple-800'>
          <div className='flex items-center gap-3 mb-6'>
            <RefreshCw className='h-6 w-6 text-red-600' />
            <h2 className='text-2xl font-bold text-gray-800 dark:text-gray-200'>
              Refund Policy
            </h2>
          </div>
          
          <div className='bg-red-50 dark:bg-red-900/20 p-6 rounded-lg border border-red-200 dark:border-red-800'>
            <div className='flex items-center gap-3 mb-3'>
              <div className='p-2 bg-red-100 dark:bg-red-900/50 rounded-lg'>
                <RefreshCw className='h-5 w-5 text-red-600' />
              </div>
              <h3 className='font-semibold text-red-800 dark:text-red-300'>No Refund Policy</h3>
            </div>
            <p className='text-red-700 dark:text-red-300 text-sm'>
              We don't offer any kind of refund for our AI services. All purchases are final. Please ensure you understand our services before making any payments.
            </p>
          </div>
        </div>

        {/* Contact Information */}
        <div className='rounded-3xl p-8 text-center'>
          <h3 className='text-xl font-semibold text-gray-800 dark:text-gray-200 mb-2'>
            Questions or Concerns?
          </h3>
          <p className='text-gray-600 dark:text-gray-300 mb-2'>
            If you have any questions about these policies, please don't hesitate to contact us.
          </p>
          <p className='font-bold text-gray-800 dark:text-gray-200 mb-2'>
            imp.communicate@gmail.com
          </p>
          <div className='flex justify-center'>
            <div className='bg-white/80 dark:bg-gray-800/80 px-6 py-3 rounded-full shadow-lg border border-purple-200 dark:border-purple-700'>
              <p className='text-sm font-medium text-gray-700 dark:text-gray-300'>
                Last updated: August 2025
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default page
